# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Security Tech Lab            # Site title
name:             D6            # Your name
avatar:           /theme/img/avatar.jpg   # Path to an avatar image
